//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePage.SendEmail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MeetingSheduled {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeetingSheduled() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnePage.SendEmail.Resources.MeetingSheduled", typeof(MeetingSheduled).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a meeting with Correia Daaveed at 10:30 today.
        /// </summary>
        public static string Correia_Daaveed {
            get {
                return ResourceManager.GetString("Correia Daaveed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a meeting with Ferreira Figueira at 11:30 today.
        /// </summary>
        public static string Ferreira_Figueira {
            get {
                return ResourceManager.GetString("Ferreira Figueira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a meeting with Gomez Kolan at 2:00 today.
        /// </summary>
        public static string Gomez_Kolan {
            get {
                return ResourceManager.GetString("Gomez Kolan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a meeting with LÇosta Morais at 3:00 today.
        /// </summary>
        public static string LÇosta_Morais {
            get {
                return ResourceManager.GetString("LÇosta Morais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a meeting with Samuel Olurotimi at 3:00 today.
        /// </summary>
        public static string Samuel_Olurotimi {
            get {
                return ResourceManager.GetString("Samuel Olurotimi", resourceCulture);
            }
        }
    }
}
