//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePage.SendEmail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewPeopleToMet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewPeopleToMet() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnePage.SendEmail.Resources.NewPeopleToMet", typeof(NewPeopleToMet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajayi Daneil       ajayidaneil1233@gmail.com.
        /// </summary>
        public static string Ajayi_Daneil {
            get {
                return ResourceManager.GetString("Ajayi Daneil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfonso Alvares  alfonsoalvares@gmail.com.
        /// </summary>
        public static string Alfonso_Alvares {
            get {
                return ResourceManager.GetString("Alfonso Alvares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amaral Amorin   amaralamorin@gmail.com.
        /// </summary>
        public static string Amaral_Amorin {
            get {
                return ResourceManager.GetString("Amaral Amorin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andrade Antune   andradeantune@gmail.com.
        /// </summary>
        public static string Andrade_Antune {
            get {
                return ResourceManager.GetString("Andrade Antune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkanj Batita     arkanjbatita@gmail.com.
        /// </summary>
        public static string Arkanj_Batita {
            get {
                return ResourceManager.GetString("Arkanj Batita", resourceCulture);
            }
        }
    }
}
