//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePage.SendEmail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PeopleToMet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PeopleToMet() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnePage.SendEmail.Resources.PeopleToMet", typeof(PeopleToMet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are meeting Borges Branco   borgesbranco@gmail.com.
        /// </summary>
        public static string Borges_Branco {
            get {
                return ResourceManager.GetString("Borges Branco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are meeting Cabral Camera  cabralcamera@gmail.com.
        /// </summary>
        public static string cabral_camera {
            get {
                return ResourceManager.GetString("cabral camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are meeting Came Campos  camecampos@gmail.com.
        /// </summary>
        public static string came_campos {
            get {
                return ResourceManager.GetString("came campos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are meeting Carneiro Chavara  carneirochavara@gmail.com.
        /// </summary>
        public static string carneiro_chavara {
            get {
                return ResourceManager.GetString("carneiro chavara", resourceCulture);
            }
        }
    }
}
